"""Add field price

Revision ID: 7066fc0335da
Revises: fa7ffefb046b
Create Date: 2025-01-06 20:35:16.379434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7066fc0335da'
down_revision: Union[str, None] = 'fa7ffefb046b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_booking_date_from'), 'booking', ['date_from'], unique=False)
    op.create_index(op.f('ix_booking_date_to'), 'booking', ['date_to'], unique=False)
    op.create_index(op.f('ix_booking_room_id'), 'booking', ['room_id'], unique=False)
    op.create_index(op.f('ix_booking_user_id'), 'booking', ['user_id'], unique=False)
    op.drop_column('booking', 'total_cost')
    op.drop_column('booking', 'total_days')
    op.add_column('hotel', sa.Column('image_url', sa.String(), nullable=False))
    op.drop_column('hotel', 'image_id')
    op.add_column('room', sa.Column('image_url', sa.String(), nullable=False))
    op.create_index(op.f('ix_room_hotel_id'), 'room', ['hotel_id'], unique=False)
    op.drop_constraint('room_hotel_id_fkey', 'room', type_='foreignkey')
    op.create_foreign_key(None, 'room', 'hotel', ['hotel_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('room', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.create_foreign_key('room_hotel_id_fkey', 'room', 'hotel', ['hotel_id'], ['id'])
    op.drop_index(op.f('ix_room_hotel_id'), table_name='room')
    op.drop_column('room', 'image_url')
    op.add_column('hotel', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('hotel', 'image_url')
    op.add_column('booking', sa.Column('total_days', sa.INTEGER(), sa.Computed('(date_to - date_from)', persisted=True), autoincrement=False, nullable=False))
    op.add_column('booking', sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), sa.Computed('(((date_to - date_from))::double precision * price)', persisted=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_booking_user_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_room_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_date_to'), table_name='booking')
    op.drop_index(op.f('ix_booking_date_from'), table_name='booking')
    # ### end Alembic commands ###
